create database orders_db;

/* единицы измерения */
create table units (
    id bigint generated by default as identity primary key,
    short_name varchar(10) not null, -- сокращённое наименование
    full_name varchar(100) not null -- полное наименование
);

/* товары */
create table goods (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description text not null,
    weight real not null,
    unit_id bigint references units(id) not null,
    price numeric not null,
    image varchar(255)
);

/* перечисление для описания статуса заказа */
create type "status" as enum ('CREATE', 'PAID', 'COLLECTION', 'READY');

/* заказы */
create table orders (
    id bigint generated by default as identity primary key,
    current_status "status" not null, -- текущий статус заказа
    total_price numeric not null -- итоговая цена
);

/* корзина с покупками */
create table baskets (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id), -- заказ
    product_id bigint references goods(id) not null, -- товар
    quantity int not null -- количество
);


